# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Designers Italia
description: La comunit√† italiana dei designer di servizi pubblici
author: Team Digitale e AgID

email: teamdigitale@governo.it
# baseurl: "/" # the subpath of your site, e.g. /blog
domain: designers.italia.it
url: "https://designers.italia.it"
twitter_username: designersITA
twitter:
  username: designersITA
github_username:  italia
piwik: teamdigitale
google_analytics: UA-3351165-20

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-toc
  - jekyll-sitemap
exclude:
  - vendor
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - circle.yml
  - gulpfile.js
  - package.json
  - yarn.lock

paginate: 10
paginate_path: "/news/page:num/"

# Custom vars
theme_color: "#0066cc"
css_theme: t-Pac
owner_short: AgID
owner_full: AgID
owner_link: http://www.agid.gov.it
logo: /assets/icons/logo-it.png
owner_logo: /assets/images/agid-logo-bb.svg
partner_short: TeamDigitale
partner_full: Team per la trasformazione digitale
partner_link: https://teamdigitale.governo.it
privacy_link: /privacy-policy
gov_logo: /assets/images/governo.svg
partner_logo: /assets/icons/dt-logo.svg #https://teamdigitale.governo.it/images/loghi/demo.png
pill:

ipress_url: https://api.ipresslive.com/v2/pressreleases/list/644fb114-0fa5-442c-8ed3-779384d7ac49?lang=it

collections:
   pages:
     output: true
     permalink: /:title/
     layout: page
   kits:
     output: true
     permalink: /kit/:title/
     layout: page
   checklists:
     output: true
     permalink: /checklist/:title/
     layout: page
   projects:
     output: true
     permalink: /progetti/:title/
     layout: project
   posts:
     output: true
     permalink: /blog/:title/
     layout: post

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      subnav: "subnav"
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      toc: true
