# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Designers Italia
description: La comunità italiana dei designer di servizi pubblici
author: Team per la Trasformazione Digitale e AgID

email: teamdigitale@governo.it
# baseurl: "/" # the subpath of your site, e.g. /blog
domain: designers.italia.it
url: "https://designers.italia.it"
twitter_username: designersITA
twitter:
  username: designersITA
github_username:  italia
piwik: a11d03a7-55e9-4c5f-89e6-20f2e7c066dc
google_analytics: UA-3351165-20
sass:
  style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-toc
  - jekyll-sitemap
exclude:
  - vendor
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - circle.yml
  - gulpfile.js
  - package.json
  - yarn.lock

paginate: 10
paginate_path: "/blog/page:num/"

# Custom vars
theme_color: "#0066cc"
css_theme: t-Pac
logo: /assets/icons/logo-it.png
owner_short: AgID
owner_full: Agenzia per l'Italia Digitale
owner_link: https://www.agid.gov.it
owner_logo: /assets/icons/logo-agid.svg
partner_short: MID
partner_full: Ministro per l’innovazione tecnologica e la digitalizzazione
partner_link: https://innovazione.gov.it/
partner_logo: /assets/icons/logo-mid.svg
privacy_link: /privacy-policy
gov_logo: /assets/images/governo.svg
funzione_pubblica_logo: /assets/images/pon/funzione_pubblica.png
eu_logo: /assets/images/pon/Unione_Europea.png
pon_logo: /assets/images/pon/pongov_1420.png
act_logo: /assets/images/pon/Agenzia_Coesione_Territoriale.png
pill:
blog_tags_directory: '/blog/tags'

# Medium posts importer / display settings
medium_archive_url: https://medium.com/designers-italia
medium_archive_url_eng: https://medium.com/designers-italia/tagged/english

collections:
   pages:
     output: true
     permalink: /:title/
     layout: page
   kits:
     output: true
     permalink: /kit/:title/
     layout: page
   checklists:
     output: true
     permalink: /checklist/:title/
     layout: page
   projects:
     output: true
     permalink: /progetti/:title/
     layout: project
   posts:
     output: true
     permalink: /blog/:title/
     layout: post

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      subnav: "subnav"
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      toc: true
