# prepare a couple reusable parameters
var_1: &cache_key v0-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
anchor_1: &job_defaults
  working_directory: /tmp/designers.italia.it
  docker:
    - image: circleci/ruby:2.5.1-node-browsers

# we use a rw SSH key instead of the default one injected by CircleCI because we
#Â use it for deploy as well
anchor_2: &add_ssh_keys
    fingerprints:
      - "4f:c4:83:7f:16:06:3e:ac:11:22:ae:c2:dd:40:d9:20"

version: 2
jobs:
  test:
    <<: *job_defaults
    steps:
      - add_ssh_keys: *add_ssh_keys
      - checkout

      #
      # Download and cache dependencies
      #
      - restore_cache:
          key: *cache_key
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Node dependencies
          command: yarn install
      - save_cache:
          key: *cache_key
          paths:
            - vendor/bundle
            - node_modules
            - ~/.cache/yarn

      # Build the site
      - run:
          name: Build
          command: npm run build

      # Test the site
      - run:
          name: Test with HTML Proofer
          command: npm run test

  deploy:
    <<: *job_defaults
    environment:
      JEKYLL_ENV: production
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - add_ssh_keys: *add_ssh_keys
      - checkout

      #
      # Download and cache dependencies
      #
      - restore_cache:
          key: *cache_key
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Node dependencies
          command: yarn install
      - save_cache:
          key: *cache_key
          paths:
            - vendor/bundle
            - node_modules
            - ~/.cache/yarn

      # Build the site
      - run:
          name: Build
          command: yarn run build

      # Test the site
      - run:
          name: Test with HTML Proofer
          command: yarn run test

      # Install rsync
      - run: mkdir -p ~/.ssh
      - run: echo $SSH_KNOWN_HOSTS | base64 -d >> ~/.ssh/known_hosts
      - run: which rsync || sudo apt-get install rsync

      # Deploy the site to the legacy server
      - run:
          name: Deploy to production
          command: yarn run deploy

      # Deploy the site to GitHub Pages
      - checkout:
          path: /tmp/gh-pages
      - deploy:
          name: Deploy
          command: |
            git config --global user.email no-reply@teamdigitale.governo.it
            git config --global user.name "Deploy Bot"

            cd /tmp/gh-pages
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .

            cp -a /tmp/designers.italia.it/_site/. .
            # copy .circleci as well so that the branch filter is honored
            mkdir -p .circleci && cp -a /tmp/designers.italia.it/.circleci/. .circleci/.

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin gh-pages

workflows:
  version: 2
  test:
      jobs:
        - test:
            filters:
              branches:
                ignore:
                  - master
                  - gh-pages
  deploy:
      jobs:
        - deploy:
            filters:
              branches:
                only:
                  - master
                  - deploy-ghpages
